src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\RegistrationEventRepository;
use Doctrine\ORM\EntityManager;
use phpDocumentor\Reflection\Types\Boolean;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateEvent;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateLimitRegistration;

    /**
     * @ORM\Column(type="integer")
     */
    private $limitParticipant;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="event", orphanRemoval=true)
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=RegistrationEvent::class, mappedBy="event", orphanRemoval=true)
     */
    private $registrationEvents;

    private $em; 

    public function __construct(EntityManager $em)
    {
        $this->messages = new ArrayCollection();
        $this->registrationEvents = new ArrayCollection();
        $this->dateEvent = new \DateTime();
        $this->dateLimitRegistration = new \DateTime(); 
        $this->limitParticipant = 10;

        $this->em = $em; 
        

    }

    public function __toString()
    {
        return $this->name; 
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateEvent(): ?\DateTimeInterface
    {
        return $this->dateEvent;
    }

    public function setDateEvent(\DateTimeInterface $dateEvent): self
    {
        $this->dateEvent = $dateEvent;

        return $this;
    }

    public function getDateLimitRegistration(): ?\DateTimeInterface
    {
        return $this->dateLimitRegistration;
    }

    public function setDateLimitRegistration(\DateTimeInterface $dateLimitRegistration): self
    {
        $this->dateLimitRegistration = $dateLimitRegistration;

        return $this;
    }

    public function getLimitParticipant(): ?int
    {
        return $this->limitParticipant;
    }

    public function getNumberParticipant()
    {   
        $nbParticipant = count($this->getRegistrationEvents());
        dump($this->em); 
        return $nbParticipant; 
    }

    public function setLimitParticipant(int $limitParticipant): self
    {
        $this->limitParticipant = $limitParticipant;

        return $this;
    }

    public function userIsRegistered(?User $user) : bool
    {
        if (!$user)
        {
            return false; 
        }
        $registrationEvents = $this->getRegistrationEvents();
        foreach ($registrationEvents as $registrationEvent) {
            if ($registrationEvent->getUser() == $user)
            {
                return true; 
            }
        }
        return false; 
    }
    public function userIsConfirmed(?User $user)
    {
        if (!$user)
        {
            return false;
        }
        $registrationEvents = $this->getRegistrationEvents();
        foreach ($registrationEvents as $registrationEvent) {
            if ($registrationEvent->getUser() == $user && $registrationEvent->getIsConfirmed())
            {
                return true; 
            }
        }
        return false;   
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setEvent($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getEvent() === $this) {
                $message->setEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|RegistrationEvent[]
     */
    public function getRegistrationEvents(): Collection
    {
        return $this->registrationEvents;
    }

    public function addRegistrationEvent(RegistrationEvent $registrationEvent): self
    {
        if (!$this->registrationEvents->contains($registrationEvent)) {
            $this->registrationEvents[] = $registrationEvent;
            $registrationEvent->setEvent($this);
        }

        return $this;
    }

    public function removeRegistrationEvent(RegistrationEvent $registrationEvent): self
    {
        if ($this->registrationEvents->contains($registrationEvent)) {
            $this->registrationEvents->removeElement($registrationEvent);
            // set the owning side to null (unless already changed)
            if ($registrationEvent->getEvent() === $this) {
                $registrationEvent->setEvent(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Event; 
use App\Entity\RegistrationEvent;
use App\Repository\EventRepository;
use App\Repository\RegistrationEventRepository;
use DateTime;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {

        // recupere la liste des event 
        $events = $this->getDoctrine()->getRepository(Event::class)->findAll(); 

        

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'events' => $events, 
        ]);
    }
    /**
     * @Route("/event/{event}", name="event")
     */
    public function event(Event $event)
    {
        $user = $this->getUser(); 
        return $this->render('main/event.html.twig', [
            'event' => $event,
            'user' => $user,
        ]); 
    }

    /**
     * @Route("/registration_event/{event}", name="registration_event")
     */
    public function registrationEvent(Event $event,  RegistrationEventRepository $repoRegistrationEvent, ValidatorInterface $validator )
    {
        // cette route permet de realisé l'inscription. 

        // on vérifie si l'utilisateur est connecté 
        $user = $this->getUser(); 
        if ($user)
        {
            dump('user is conneted'); 
            // l'utilisateur est connecté, on récuperer les information. 

            // on crée l'objet registration event. 
            $registrationEvent = new RegistrationEvent; 
            // on stocke les data dans l'objet 
            $registrationEvent
                ->setEvent($event)
                ->setUser($user)
                ->setRegistrationDate(New \DateTime()); 

            // on vérifie si il a encore de la place pour event 
            $currentparticipantForEvent =  count($repoRegistrationEvent->findBy(['event' => $event])); 
            dump($currentparticipantForEvent); 
            if ( $event->getLimitParticipant() >= $currentparticipantForEvent)
            {
                // il reste de la place pour l'event, on confirme sa participation à l'event. 
                $registrationEvent->setIsConfirmed(true); 
            }

            // on vérifie les donnée 
            $errors = $validator->validate($registrationEvent); 

            dump($errors); 

            if (count($errors) == 0)
            {
                // on enregistre inscription dans la BDD
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($registrationEvent);
                $entityManager->flush(); 

                // message flash 
                $this->addFlash('notice', 'Tu es inscrit à l\'event');

                // on envoie un mail à l'utilisateur pour la confirmation d'inscription 
                // mailManager->sendComfirmation($registrationEvent)

            }
            else
            {
                $this->addFlash('error', $errors); 
            }
            
            // changé en redirect to route ( risque de partage du lien qui fais mal ) 
            return $this->redirectToRoute('event', ['event' => $event->getId()]); 
            
        }

        // utilisateur n'est pas connecté, on le dirige vers la page de login
        return $this->redirectToRoute('app_login'); 
        // temporaire, je veux rester sur la page lors du débug pour intercepter les dump 
        //return $this->render('base.html.twig'); 
    }

    /**
     * @route("/cancel_registration_event/{event}" ,  name="cancel_registration_event")
     */
    public function cancelRegistrationEvent(Event $event, RegistrationEventRepository $repoRegistrationEvent)
    {
        $user = $this->getUser();
        if ($user)
        {
            // l'utilisateur est connecté 

            // on recupere l'enregistrement en recherchant avec user et id de l'event 
            $registrationEvent = $repoRegistrationEvent->findOneBy(['event' => $event, 'user' => $user]);
            // on vérifie si l'enregistrement est trouvé 
            if ($registrationEvent)
            {
                // enregistrement existe, on peut supprimer de la BDD
                $entityManager = $this->getDoctrine()->getManager(); 
                $entityManager->remove($registrationEvent); 

                $entityManager->flush();

                $this->addFlash('notice', 'Annulation effectué'); 
                
            }
            else
            {
                // enregistrement n'exite pas, on lance une exception

                $this->addFlash('error', 'pas de registration'); 

                // on lance la vérification de la liste d'attente

            }
        }
        else 
        {
            $this->addFlash('error', 'utilisateur non connecté'); 
        }

        return $this->redirectToRoute('event', ['event' => $event->getId()]); 
    }

    /**
     * @route("/profile", name="profile")
     */
    public function profileDashboard()
    {
        $user = $this->getUser(); 
        if ($user)
        {
            $hashUserGravatar = md5($user->getEmail());
            dump($hashUserGravatar); 
            // utilisateur est connecté, on affiche la page profile.
            return $this->render('main/profile.html.twig', [
                'hashusergravatar' => $hashUserGravatar, 
            ]); 
        }
        // l'utilsateur n'est pas connecté, on le redirige vers la page de login 
        return $this->redirectToRoute('app_login');
    }

}

templates/main/event.html.twig
{% extends 'base.html.twig' %}

{# cette page est la page de evenement, elle doit afficher le détail de evenement  #}

{% block title %}{{ event.name }}{% endblock %}

{% block body %}

{# affichage des flash message si il en a #}

{# read and display all flash messages #}
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="flash-{{ label }}">
            {{ message }}
        </div>
    {% endfor %}

    {% else %}
    <span> Pas de flash message ( juste pour le test ) </span>
{% endfor %}

<h1>{{ event.name }}</h1>

<p>{{ event.description }}</p>





<span>Nombre de place : {{ event.limitParticipant }}</span></br>
<span>Nombre d'inscrit : {{ event.numberParticipant }}</span></br>

{% if event.userIsRegistered(app.user) %}
<span>Vous etes inscrit à l'event</span>
{% else %}
<span>Vous n'est pas inscrit à l'event</span>
{% endif %}

{% if event.userIsConfirmed(app.user) %}
<span>Votre inscription est confirmé</span>
{% else %}
<span>Vous etes dans la liste d'attente</span>
{% endif %}

<hr>

{% if event.userIsRegistered(app.user) %}

<a href="{{ path('cancel_registration_event' , {event: event.id}) }}" >se désincrire</a>
{% else %}
<a href="{{ path('registration_event', {event: event.id}) }}" >S'inscrire</a><br/>
{% endif %}

<footer>
    <a href="{{ path('home') }}">Retour à la liste d'event</a>
</footer>

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{# cette page est la home page, elle doit afficher la liste des Event #}

{% block title %}Event{% endblock %}

{% block body %}


<div>

    {% if app.user %}
    {# on affiche les information de l'utilisateur #}
    <div>   
        <span><strong>Prénom : </strong> {{ app.user.firstname }}</span><br/>
        <span><strong>Noms : </strong> {{ app.user.lastname|upper }}</span>
    </div>
    {% endif %}


    <h1>Liste des Events</h2>
    
    
        {% for event in events %}
        <div>
            <h2>{{ event.name }}</h2>
            <p>{{ event.description }}</h2>
            <a href="{{ path('event', {event: event.id}) }}" >voir event en détail </a>
        </div>
        {% endfor %}
    
</div>
{% endblock %}

templates/main/profile.html.twig
{# ceci est la page profile, elle contiendra tous les information de l'utilisateur : prénom, nom, mail, modification du MDP #}

{% extends "base.html.twig" %}

{% block title %}Profile{% endblock %}  

{% block body %}
    <h1>Page profile</h1>
    
    <span><strong>Prénom : </strong>{{ app.user.firstname }}</span><br/>
    <span><strong>Nom : </strong>{{ app.user.lastname }}</span><br/>
    <span><strong>Email : </strong>{{ app.user.email }}</span><br/>

    <span><strong>Avatar : </strong></span>
    <img id="avatar" src="https://secure.gravatar.com/avatar/{{ hashusergravatar }}" alt="photo-{{ app.user.firstname }}">

    {# mon hash : a6ccd52ac092b6548a22496c995670fd #}

{% endblock %}

{% block javascripts %}
{# juste pour le test #}
<script>
    
</script>

{% endblock %}